stages:
    - build
build:
    stage: build
    tags:
    - immersive-runner-cgi
    image: maven:latest
    script:
        - echo "hello world"
        - mvn clean package test
        - mkdir build
        - touch build/info.txt
