version: '3'
services:
 zuul:
  image: zuul-service
  build: zuul-service/
  restart: always
  network_mode: host
  container_name: zuul-service
  ports:
    - 8081:8081
  expose:
    - 8081
 
 eureka:
  image: eureka-service
  build: eureka-service/
  restart: always
  network_mode: host
  container_name: eureka-service
  ports:
    - 8761:8761
  expose:
    - 8761
 config:
  image: config-service
  build: config-service/
  restart: always
  network_mode: host
  container_name: config-service
  ports:
    - 8888:8888
  expose:
    - 8888
  
